version: "3.9"

services:
  
  main_gui:
    build:
      dockerfile: Dockerfile
    image: chatsql:latest
    volumes:
      - /data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [ "gpu" ]
    ports:
      - "5677:8000"
    entrypoint: [
      "python3", "main_gui.py"
    ]

  main_gui_moss:
    build:
      dockerfile: Dockerfile
    image: chatsql:latest
    volumes:
      - /data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [ "gpu" ]
    ports:
      - "5678:8000"
    entrypoint: [
      "python3", "main_gui_moss.py"
    ]