version: "3.9"

services:
  
  main_gui:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatsql:latest
    ports:
      - "5677:8000"
    entrypoint: [
      "python3", "main_gui.py"
    ]

  main_gui_moss:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatsql:latest
    ports:
      - "5678:8000"
    entrypoint: [
      "python3", "main_gui_moss.py"
    ]